apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: g8u0w60ll-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/g8u0w60ll-java-quarkus-gitops